export const SET_ACTIVE_SELECTED_MOVIE = 'SET_ACTIVE_SELECTED_MOVIE';
export const SET_SOURCE_MOVIE_DATA = 'SET_SOURCE_MOVIE_DATA';
export const REMOVE_ITEM_TO_CARD = 'REMOVE_ITEM_TO_CARD';
export const ADD_ITEM_TO_CARD = 'ADD_ITEM_TO_CARD';


