import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import { GENRE_LIST_DATA_SERVER_ENDPOINT, MOVIE_LIST_DATA_SERVER_ENDPOINT } from '../utilities/config';
import { ILandingScreenStyleProps } from '../utilities/interfaces/landingTypes';
import MovieListingBlock from '../components/MovieListingBlock/MovieListingBlock';
import MovieHead from '../components/shared/MovieHead/MovieHead';

export default function Home(props: ILandingScreenStyleProps) {
  const { movieListData, genresData } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MovieHead />
      <MovieListingBlock
        movieListData={movieListData}
        genresData={genresData}
      />

      <footer className={styles.footer}>
        <a
          href="#"
          target="#"
          rel="noopener noreferrer"
        >
          Powered by Emaar
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context: any) {

  let movieListData = [];
  let genresData = [];
  [{ data: movieListData }, { data: genresData }] = await Promise.all([
    axios.get(`${MOVIE_LIST_DATA_SERVER_ENDPOINT}`),
    axios.get(`${GENRE_LIST_DATA_SERVER_ENDPOINT}`),
  ]);
  genresData.genres.push({id: 0, name: 'All'});
  genresData.genres.sort((a:any, b: any) => a.id - b.id);
  return {
    props: {
      movieListData,
      genresData: genresData.genres ,
    }
  }
}
